import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCategories = async () => {
  try {
    const res = await fetch("https://dummyjson.com/products/categories");
    const data = await res.json();
    return data;
  } catch (error) {}
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await getCategories();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar categories={categories} />
        {children}
        <Footer categories={categories} />
      </body>
    </html>
  );
}
